### ISSUE TITLE
[Enhancement] Consider using CDNs for bootstrap and other common libraries

### ISSUE THREAD

**Issue by tannerstephens** [mstacm/acmsec.mst.edu#20]
CDNs, especially those of popular libraries, allow your page to load faster as users will have the big CSS and JS files already in their browser cache. It also eliminates extra overhead for your webserver

**Comment by Portal2Mtr** [comment]
I saw some other sites using this and it makes sense for faster load times. I wasn't sure how to create custom styles on top of CDNs, so I just used a local SASS compiler instead. Looking at it more now, I see there should be ways to do custom styles and use CDNs, so I'm open to switching. The MDB files have a bit of custom CSS on top of the base file, so getting that to work with the MDB CDN is a good starting point.
